### ISSUE TITLE
Enable Nullable Reference Types

### ISSUE THREAD

**Issue by gautamomento** [momentohq/client-sdk-csharp#14]
better null-safe typing if you enable it in your project files:
https://devblogs.microsoft.com/dotnet/try-out-nullable-reference-types/#try-out-nullable-reference-types

https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references#nullable-contexts

**Comment by malandis** [comment]
Fixed in https://github.com/momentohq/client-sdk-csharp/commit/10bcf251297288ce17e2a57a06e62c7add2532ec
